version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod --smallfiles
    volumes:
     - ./var/mongo:/data

#  mysql:
#    image: mysql:latest
#    ports:
#      - 9999:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=123qweasd
#      - MYSQL_ROOT_HOST=172.18.0.1
#      - MYSQL_DATABASE=rexoubador
#      - MYSQL_PASSWORD=123qweasd

#  rexoubador-api:
#    image: java:openjdk-8u91-jdk
#    working_dir: /app
#    volumes:
#      - ./build/libs:/app
#    command: java -jar /app/rexoubador-api-0.1.0.jar
#    depends_on:
#      - mysql
#      - mongodb
#      - rabbitmq
#    links:
#      - mysql
#      - mongodb
#      - rabbitmq
#    ports:
#      - 8081:8080
#    environment:
#      - DATABASE_HOST=demo
#      - DATABASE_USER=dbuser
#      - DATABASE_PASSWORD=dbp4ss
#      - DATABASE_NAME=demo
#      - DATABASE_PORT=3306