version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod --smallfiles
    volumes:
     - ./var/mongo:/data
    networks:
      - backend

  mysql:
    image: mysql:latest
    ports:
      - 9999:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123qweasd
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=rexoubador
      - MYSQL_USER=rexoubador
      - MYSQL_PASSWORD=rexoubador
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
         aux_addresses:
          mysql: 10.5.0.5
          mongodb: 10.5.0.6
          rabbitmq: 10.5.0.7