debug: true
# DataSource settings: set here your own configurations for the database
# connection. In this example we have "netgloo_blog" as database name and
# "root" as username and password.
jwt:
  header: Authorization
  secret: my-very-secret-key
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:8889/rexoubador
    username: rexoubador
    password: 123qweasd
    driver-class-name: com.mysql.jdbc.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager).
# Show or not log for each sql query
  jpa:
    show-sql: true
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rexoubador
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: true # set to false to disable 'default' Spring Boot security

rexoubador:
  publicSSHKey: "THE PUBLIC KEY"
  privateKeyPath: "/Users/edusalguero/.ssh/id_rsa"
  passphrase:   "edusalguero"